#!/bin/sh
## this script should be run as root

# SSH keys from github
apt-get install -y curl
curl -github.com/declercklouis.keys > /root/.ssh/authorized_keys
curl -github.com/declercklouis.keys > /home/declercklouis/.ssh/authorized_keys
chown declercklouis:declercklouis /home/declercklouis/.ssh/authorized_keys

# docker installation
## adding docker gpg key
apt-get update
apt-get install -y ca-certificates curl gnupg
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
chmod a+r /etc/apt/keyrings/docker.gpg

## adding docker repository
echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
apt-get update -y

## installing docker
apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

## adding user to docker group
usermod -aG docker $USER
usermod -aG docker declercklouis


# ansible installation
apt install -y ansible ansible-lint